# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-22 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('sha1', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('service', models.CharField(max_length=140)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('name', 'service')]),
        ),
    ]
